export enum ValidationFieldTypeEnum {
  text = 'text',
  select = 'select',
  localSearch = 'localSearch',
  search = 'search',
  dataRange = 'dateRange',
  date = 'date',
  time = 'time',
  file = 'file',
  maltyFile = 'maltyFile',
  dropFile = 'dropFile',
  checkbox = 'checkbox',
  number = 'number',
  password = 'password',
  email = 'email',
  textArea = 'textArea',
}
